### ISSUE TITLE
Running end-to-end-lane follower on TPU

### ISSUE THREAD

**Issue by patrickpoirier51** [dctian/DeepPiCar#5]
Hello, 
I am interesting to build and experiment, but I am missing a step....

You are training with Nvidia Model and generate a h5 file.
Then you run the follower script using this file : lane_navigation.h5

Question: I there a supplemental step I am missing to get this KERAS file running with TPU ?

**Comment by dctian** [comment]
Nvidia Lane navigation model is not a very deep network, so the keras h5 model file can run on Pi CPU very quickly, at least 20-30 Frames per second.
However, the traffic sign detection model (MobileNet V2 with SSD) is a very deep network, and needs to run on the TPU.  Please refer to Part 6 of DeepPiCar blog on how to do traffic sign detection. Hope this help!
